_base_: default.yml
model_name: default
checkpoint:
  resume: ''
model:
  clip_model_name: ViT-B/16
  keep_cls: false
  keep_end_seq: false
# 新增的参数
  # with_bg_clean: true
  # lambda_bg: 0.5

  model_name: vit_large_patch16_dinov3.lvd1689m
  proj_class: dinov3_vitl_mlp_infonce
  proj_model: ProjectionLayer
  proj_name: dinov3_vitl_mlp_infonce_lvd1689m_rs3_best_epoch99
  # proj_name: dinov3_vitl_mlp_infonce_lvd1689m_pub11
  # proj_name: dinov3_vitl_mlp_infonce_lvd1689m_git10m_best_epoch100
  # proj_name: dinov3_vitl_mlp_infonce_average_lvd1689m_rs3_best_epoch99 #去掉AFA模块
  # resize_dim: 512 #默认
  resize_dim: 1024
  type: DINOText
  use_avg_text_token: false
