evaluate:
  # pamr: true #默认
  pamr: false
  bg_thresh: 0.5
  # kp_w: 0.3 #默认
  kp_w: 0

  pred_qual_path: null
  gt_qual_path: null

  eval_only: true
  template: sub_imagenet_template
  task:
    - vdd

  vdd: src/open_vocabulary_segmentation/segmentation/configs/_base_/datasets/vdd.py

seed: 42
