evaluate:
  # pamr: true  #默认
  pamr: false
  bg_thresh: 0.4 #默认，没有背景不用改这个参数

  # kp_w: 0.3 #默认
  kp_w: 0

  pred_qual_path: null
  gt_qual_path: null

  eval_only: true
  template: sub_imagenet_template
  task:
    - dlrsd

  dlrsd: src/open_vocabulary_segmentation/segmentation/configs/_base_/datasets/dlrsd.py


seed: 42
