evaluate:
  # pamr: true  #默认
  pamr: false
  bg_thresh: 0.4
  # kp_w: 0.3 #默认
  kp_w: 0

  pred_qual_path: null
  gt_qual_path: null

  eval_only: true
  template: sub_imagenet_template
  task:
    - whdld

  whdld: src/open_vocabulary_segmentation/segmentation/configs/_base_/datasets/whdld.py


seed: 42
