_base_: default.yml
model_name: default
checkpoint:
  resume: ''
model:
  clip_model_name: ViT-B/16
  keep_cls: false
  keep_end_seq: false
  model_name: vit_large_patch16_dinov3.sat493m
  proj_class: dinov3_vitl_mlp_infonce
  proj_model: ProjectionLayer
  proj_name: dinov3_vitl_mlp_infonce_sat493m_pub11
  resize_dim: 512
  type: DINOText
  use_avg_text_token: false

