_base_: default.yml
model_name: default
checkpoint:
  resume: ''
model:
  clip_model_name: ViT-B/16
  keep_cls: false
  keep_end_seq: false
  model_name: dinov2_vitb14_reg
  proj_class: vitb_mlp_infonce
  proj_model: ProjectionLayer
  proj_name: vitb_mlp_infonce_rsicd
  resize_dim: 448
  type: DINOText
  use_avg_text_token: false
