evaluate:
  # pamr: true  #默认
  pamr: false
  bg_thresh: 0.588 #rs3默认最好
  # bg_thresh: 0.58  #pub11默认最好
  # bg_thresh: 0.572  #git10m默认最好
  # kp_w: 0.3
  kp_w: 0

  pred_qual_path: null
  gt_qual_path: null

  eval_only: true
  template: sub_imagenet_template
  task:
    - isaid

  isaid: src/open_vocabulary_segmentation/segmentation/configs/_base_/datasets/isaid.py

seed: 42
